
package pet.orca.bukkit.cartsummoner;

import org.bukkit.Material;
import org.bukkit.block.Block;
import org.bukkit.block.BlockState;

import com.google.common.collect.Sets;

import java.util.Set;

import lombok.experimental.Delegate;

public class MaterialFamily implements Set<Material> {

	@Delegate
	private final Set<Material> materials;

	public MaterialFamily(Set<Material> materials) {
		this.materials = Sets.immutableEnumSet(materials);
	}

	public MaterialFamily(Material ... materials) {
		this.materials = Sets.immutableEnumSet(materials[0], materials);
	}

	public boolean hasMaterial(Block block) {
		return contains(block.getType());
	}

	public boolean hasMaterial(BlockState block) {
		return contains(block.getType());
	}

	public static final MaterialFamily SAFE_AIR_BLOCKS = new MaterialFamily(
		Material.AIR,
		Material.OAK_SAPLING,
		Material.SPRUCE_SAPLING,
		Material.BIRCH_SAPLING,
		Material.JUNGLE_SAPLING,
		Material.ACACIA_SAPLING,
		Material.DARK_OAK_SAPLING,
		Material.OAK_LEAVES,
		Material.SPRUCE_LEAVES,
		Material.BIRCH_LEAVES,
		Material.JUNGLE_LEAVES,
		Material.ACACIA_LEAVES,
		Material.DARK_OAK_LEAVES,
		Material.POWERED_RAIL,
		Material.DETECTOR_RAIL,
		Material.GRASS,
		Material.FERN,
		Material.DEAD_BUSH,
		Material.SEAGRASS,
		Material.DANDELION,
		Material.POPPY,
		Material.BLUE_ORCHID,
		Material.ALLIUM,
		Material.AZURE_BLUET,
		Material.RED_TULIP,
		Material.ORANGE_TULIP,
		Material.WHITE_TULIP,
		Material.PINK_TULIP,
		Material.OXEYE_DAISY,
		Material.CORNFLOWER,
		Material.LILY_OF_THE_VALLEY,
		Material.WITHER_ROSE,
		Material.BROWN_MUSHROOM,
		Material.RED_MUSHROOM,
		Material.CRIMSON_FUNGUS,
		Material.WARPED_FUNGUS,
		Material.CRIMSON_ROOTS,
		Material.WARPED_ROOTS,
		Material.NETHER_SPROUTS,
		Material.WEEPING_VINES,
		Material.TWISTING_VINES,
		Material.SUGAR_CANE,
		Material.KELP,
		Material.TORCH,
		Material.END_ROD,
		Material.LADDER,
		Material.RAIL,
		Material.LEVER,
		Material.STONE_PRESSURE_PLATE,
		Material.OAK_PRESSURE_PLATE,
		Material.SPRUCE_PRESSURE_PLATE,
		Material.BIRCH_PRESSURE_PLATE,
		Material.JUNGLE_PRESSURE_PLATE,
		Material.ACACIA_PRESSURE_PLATE,
		Material.DARK_OAK_PRESSURE_PLATE,
		Material.CRIMSON_PRESSURE_PLATE,
		Material.WARPED_PRESSURE_PLATE,
		Material.POLISHED_BLACKSTONE_PRESSURE_PLATE,
		Material.REDSTONE_TORCH,
		Material.SNOW,
		Material.SOUL_TORCH,
		Material.MUSHROOM_STEM,
		Material.CHAIN,
		Material.VINE,
		Material.LILY_PAD,
		Material.TRIPWIRE_HOOK,
		Material.STONE_BUTTON,
		Material.OAK_BUTTON,
		Material.SPRUCE_BUTTON,
		Material.BIRCH_BUTTON,
		Material.JUNGLE_BUTTON,
		Material.ACACIA_BUTTON,
		Material.DARK_OAK_BUTTON,
		Material.CRIMSON_BUTTON,
		Material.WARPED_BUTTON,
		Material.POLISHED_BLACKSTONE_BUTTON,
		Material.LIGHT_WEIGHTED_PRESSURE_PLATE,
		Material.HEAVY_WEIGHTED_PRESSURE_PLATE,
		Material.ACTIVATOR_RAIL,
		Material.WHITE_CARPET,
		Material.ORANGE_CARPET,
		Material.MAGENTA_CARPET,
		Material.LIGHT_BLUE_CARPET,
		Material.YELLOW_CARPET,
		Material.LIME_CARPET,
		Material.PINK_CARPET,
		Material.GRAY_CARPET,
		Material.LIGHT_GRAY_CARPET,
		Material.CYAN_CARPET,
		Material.PURPLE_CARPET,
		Material.BLUE_CARPET,
		Material.BROWN_CARPET,
		Material.GREEN_CARPET,
		Material.RED_CARPET,
		Material.BLACK_CARPET,
		Material.SUNFLOWER,
		Material.LILAC,
		Material.ROSE_BUSH,
		Material.PEONY,
		Material.TALL_GRASS,
		Material.LARGE_FERN,
		Material.TUBE_CORAL,
		Material.BRAIN_CORAL,
		Material.BUBBLE_CORAL,
		Material.FIRE_CORAL,
		Material.HORN_CORAL,
		Material.DEAD_BRAIN_CORAL,
		Material.DEAD_BUBBLE_CORAL,
		Material.DEAD_FIRE_CORAL,
		Material.DEAD_HORN_CORAL,
		Material.DEAD_TUBE_CORAL,
		Material.TUBE_CORAL_FAN,
		Material.BRAIN_CORAL_FAN,
		Material.BUBBLE_CORAL_FAN,
		Material.FIRE_CORAL_FAN,
		Material.HORN_CORAL_FAN,
		Material.DEAD_TUBE_CORAL_FAN,
		Material.DEAD_BRAIN_CORAL_FAN,
		Material.DEAD_BUBBLE_CORAL_FAN,
		Material.DEAD_FIRE_CORAL_FAN,
		Material.DEAD_HORN_CORAL_FAN,
		Material.IRON_DOOR,
		Material.OAK_DOOR,
		Material.SPRUCE_DOOR,
		Material.BIRCH_DOOR,
		Material.JUNGLE_DOOR,
		Material.ACACIA_DOOR,
		Material.DARK_OAK_DOOR,
		Material.CRIMSON_DOOR,
		Material.WARPED_DOOR,
		Material.REPEATER,
		Material.COMPARATOR,
		Material.STRING,
		Material.WHEAT,
		Material.OAK_SIGN,
		Material.SPRUCE_SIGN,
		Material.BIRCH_SIGN,
		Material.JUNGLE_SIGN,
		Material.ACACIA_SIGN,
		Material.DARK_OAK_SIGN,
		Material.CRIMSON_SIGN,
		Material.WARPED_SIGN,
		Material.CAKE,
		Material.WHITE_BED,
		Material.ORANGE_BED,
		Material.MAGENTA_BED,
		Material.LIGHT_BLUE_BED,
		Material.YELLOW_BED,
		Material.LIME_BED,
		Material.PINK_BED,
		Material.GRAY_BED,
		Material.LIGHT_GRAY_BED,
		Material.CYAN_BED,
		Material.PURPLE_BED,
		Material.BLUE_BED,
		Material.BROWN_BED,
		Material.GREEN_BED,
		Material.RED_BED,
		Material.BLACK_BED,
		Material.FLOWER_POT,
		Material.SKELETON_SKULL,
		Material.WITHER_SKELETON_SKULL,
		Material.PLAYER_HEAD,
		Material.ZOMBIE_HEAD,
		Material.CREEPER_HEAD,
		Material.DRAGON_HEAD,
		Material.BELL,
		Material.TALL_SEAGRASS,
		Material.WALL_TORCH,
		Material.REDSTONE_WIRE,
		Material.OAK_WALL_SIGN,
		Material.SPRUCE_WALL_SIGN,
		Material.BIRCH_WALL_SIGN,
		Material.ACACIA_WALL_SIGN,
		Material.JUNGLE_WALL_SIGN,
		Material.DARK_OAK_WALL_SIGN,
		Material.REDSTONE_WALL_TORCH,
		Material.SOUL_WALL_TORCH,
		Material.ATTACHED_PUMPKIN_STEM,
		Material.ATTACHED_MELON_STEM,
		Material.PUMPKIN_STEM,
		Material.MELON_STEM,
		Material.TRIPWIRE,
		Material.CARROTS,
		Material.POTATOES,
		Material.SKELETON_WALL_SKULL,
		Material.WITHER_SKELETON_WALL_SKULL,
		Material.ZOMBIE_WALL_HEAD,
		Material.PLAYER_WALL_HEAD,
		Material.CREEPER_WALL_HEAD,
		Material.DRAGON_WALL_HEAD,
		Material.BEETROOTS,
		Material.DEAD_TUBE_CORAL_WALL_FAN,
		Material.DEAD_BRAIN_CORAL_WALL_FAN,
		Material.DEAD_BUBBLE_CORAL_WALL_FAN,
		Material.DEAD_FIRE_CORAL_WALL_FAN,
		Material.DEAD_HORN_CORAL_WALL_FAN,
		Material.TUBE_CORAL_WALL_FAN,
		Material.BRAIN_CORAL_WALL_FAN,
		Material.BUBBLE_CORAL_WALL_FAN,
		Material.FIRE_CORAL_WALL_FAN,
		Material.HORN_CORAL_WALL_FAN,
		Material.BAMBOO_SAPLING,
		Material.WEEPING_VINES_PLANT,
		Material.TWISTING_VINES_PLANT,
		Material.CRIMSON_WALL_SIGN,
		Material.WARPED_WALL_SIGN
	);

	public static final MaterialFamily BUTTONS = new MaterialFamily(
		Material.STONE_BUTTON,
		Material.OAK_BUTTON,
		Material.SPRUCE_BUTTON,
		Material.BIRCH_BUTTON,
		Material.JUNGLE_BUTTON,
		Material.ACACIA_BUTTON,
		Material.DARK_OAK_BUTTON,
		Material.CRIMSON_BUTTON,
		Material.WARPED_BUTTON,
		Material.POLISHED_BLACKSTONE_BUTTON
	);

	public static final MaterialFamily RAILS = new MaterialFamily(
		Material.POWERED_RAIL,
		Material.DETECTOR_RAIL,
		Material.RAIL,
		Material.ACTIVATOR_RAIL
	);
}
